---
title: "eBirdst"
author: "Andres N. Rosales"
date: "2024-09-04"
output: 
  html_document: 
    highlight: espresso
    toc: yes
    theme: sandstone
---

# Chapter 1 eBird st code

This code extracts and manipulates eBird status and trends data for the first chapter of my thesis. More infomation and visualizations can be found at <https://science.ebird.org/en/status-and-trends/species/uplsan/trends-map>

## Library

```{r}


library(dplyr)
library(ggplot2)
library(rnaturalearth)
library(sf)
library(terra)
library(ebirdst)


```





## Extract
This code views and extracts available st data for Upland Sandpiper.

```{r}
#Set unique key to access eBirdst data (expires Jan 18th 2025)
set_ebirdst_access_key("3t1ddtda3uh3", overwrite = TRUE)

```


```{r}

# shows all species with st data available
trends_runs <- ebirdst_runs %>% 
  filter(has_trends) %>% 
  select(species_code, common_name,
         trends_season, trends_region,
         trends_start_year, trends_end_year,
         trends_start_date, trends_end_date,
         rsquared, beta0)
#subset to UPSA available data for viewing
upsa <- trends_runs %>% 
  filter(common_name == "Upland Sandpiper") %>% 
  select(trends_start_year, trends_end_year, 
         trends_start_date, trends_end_date)

upsa

```

```{r}
#create object with trends 
trends <- load_trends("uplsan")

(trends)
```

### Strimas-Mackey Upland Sandpiper data (2007-2021) 

```{r}

long_trend <- read.csv("/Users/ROSALESA/OneDrive - University of Saskatchewan/17_Analysis/Chapter1/eBird trend data/prairie analysis/PHJV_trends.csv")
str(long_trend)

#create col for confidence interval non zero, 1 is True, 0 is False
long_trend$abd_ppy_nonzero <- NA
long_trend$abd_ppy_nonzero <- as.factor(long_trend$abd_ppy_nonzero)

#ifelse statement to label that pixel if overlapping zero
long_trend$abd_ppy_nonzero <- ifelse(long_trend$abd_ppy_lower > 0 | long_trend$abd_ppy_upper < 0, 1, 0)

#subset only significant trends with high confidence
sig_trends <- subset(long_trend, abd_ppy_nonzero == "1")

#apply compund interest to trend to get cumulative trend 
#abd_trend: the median estimated cumulative change in relative abundance over the trend time period
#equation:abd_trend <- 100 * ((1 + abd_ppy / 100)^(2021 - 2007) - 1)

sig_trends$abd_trend <- NA
sig_trends$abd_trend <- 100 * ((1 + sig_trends$abd_ppy / 100)^(2021 - 2007) - 1)

sig_trends
```




















## Session Info
```{r}
sessionInfo()
```

