---
title: "Predictors"
author: "Andres N. Rosales"
date: "2024-11-11"
output:
  html_document:
    highlight: espresso
    toc: yes
    theme: sandstone
  pdf_document:
    toc: yes
  word_document:
    toc: yes
---

This code creates spatial buffers using the 'sf' package and calcualtes 
metrics using the 'landscape metrics package'.

# Library
```{r}

library(dplyr)
library(purrr)
library(ggplot2)
library(rnaturalearth)
library(sf)
library(raster)
library(terra)
library(tinytex)
library(rmarkdown)
library(knitr)
library(ebirdst)
library(exactextractr)
library(landscapemetrics)
library(readr)
library(stringr)
library(tidyr)
library(units)
library(viridis)
library(progress)
library(dplyr)

```

# PHJV 
## Load Spatial Buffer
```{r}
#Load PHJV buffers we made in the ebirdst.rmd file
phjv_buff <- st_read("Predictor_buffer/utrd_buff_PHJV.gpkg", layer = "ubuffPHJV") #shapefile should be in WGS43


ggplot() +
  geom_sf(data = phjv_buff, fill = "lightgreen", color = "darkgreen", alpha = 0.5) +
  theme_minimal() +
  labs(title = "13.5 km Circular Buffers", x = "Longitude", y = "Latitude")
op <- options_landscapemetrics()

```



```{r}
#Load Canada rasters classified for composition metrics. These rasters are classified for compositon metrics and is only land cover for Canada.
can_rasters <- list(
  "2012" = rast("C:/Users/Andres/OneDrive - University of Saskatchewan/04_landcover/04_predictor_code/Canada_comp/2012.tif"),
  "2013" = rast("C:/Users/Andres/OneDrive - University of Saskatchewan/04_landcover/04_predictor_code/Canada_comp/2013.tif"),
  "2014" = rast("C:/Users/Andres/OneDrive - University of Saskatchewan/04_landcover/04_predictor_code/Canada_comp/2014.tif"),
  "2015" = rast("C:/Users/Andres/OneDrive - University of Saskatchewan/04_landcover/04_predictor_code/Canada_comp/2015.tif"),
  "2016" = rast("C:/Users/Andres/OneDrive - University of Saskatchewan/04_landcover/04_predictor_code/Canada_comp/2016.tif"),
  "2017" = rast("C:/Users/Andres/OneDrive - University of Saskatchewan/04_landcover/04_predictor_code/Canada_comp/2017.tif"),
  "2018" = rast("C:/Users/Andres/OneDrive - University of Saskatchewan/04_landcover/04_predictor_code/Canada_comp/2018.tif"),
  "2019" = rast("C:/Users/Andres/OneDrive - University of Saskatchewan/04_landcover/04_predictor_code/Canada_comp/2019.tif"),
  "2020" = rast("C:/Users/Andres/OneDrive - University of Saskatchewan/04_landcover/04_predictor_code/Canada_comp/2020.tif"),
  "2021" = rast("C:/Users/Andres/OneDrive - University of Saskatchewan/04_landcover/04_predictor_code/Canada_comp/2021.tif"),
  "2022" = rast("C:/Users/Andres/OneDrive - University of Saskatchewan/04_landcover/04_predictor_code/Canada_comp/2022.tif")
)
```

```{r}
#calcualte lsm for 2012 for pland and ed (need to change to all years and change metrics)
lsm_pg <- NULL
for (i in seq_len(nrow(phjv_buff))) {
  buffer_i <- st_transform(phjv_buff[i, ], crs = crs(can_rasters[["2012"]]))
  
  # Crop and mask the landcover raster so all values outside buffer are missing
  lsm_pg[[i]] <- crop(can_rasters[["2012"]], buffer_i) |> 
    mask(buffer_i) |> 
    # Calculate landscape metrics
    calculate_lsm(level = "class", metric = c("pland", "ed")) |> 
    # Add variable to uniquely identify each point
    mutate(srd_id = buffer_i$srd_id) |> 
    dplyr::select(srd_id, class, metric, value)
}

# Combine results into a single data frame
lsm_pg <- bind_rows(lsm_pg)



# transform to wide format 
lsm_wide_pg <- lsm_pg |> 
  # fill missing classes with zeros
  complete(srd_id,
           class = lc_classes$class,
           metric = c("ed", "pland"),
           fill = list(value = 0)) |> 
  # bring in more descriptive names
  inner_join(select(lc_classes, class, label), by = "class") |> 
  # transform from long to wide format
  pivot_wider(values_from = value,
              names_from = c(class, label, metric),
              names_glue = "{metric}_c{str_pad(class, 2, pad = '0')}_{label}",
              names_sort = TRUE,
              values_fill = 0) |> 
  arrange(srd_id)
```

